### ISSUE TITLE
Cannot make buy offer 404 not found

### ISSUE THREAD

**Issue by dataexcess** [nina-protocol/nina#1074]
Today I wanted to create a buy offer to buy Glint's awesome '2 times too' track for 10 USDC.
I couldn't complete the action and got the following error:

```
trycatch.js:165     GET https://api.ninaprotocol.com/v1/exchanges/CaBPERZX5FeetPUc7HMz8iwek5yrSHDXsRQXxo42d1Ex?transactionId=4pDp79yRV9d5AUmQU9qL2ESYj3TpYhiRRihggejGfbbFRGN41qXsgotagmY9JjX2y18QBY8FeoazKTCyevti51Ka 404 (Not Found)
instrument.js:111 Error: Request failed with status code 404
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.b (xhr.js:54:7)
```

**Comment by facing-n** [comment]
thanks for this - we will take a look and get back to you with findings
